# -*- coding: utf-8 -*-
"""
아트잡스 수집 대상 사이트 대장(臺帳) — 예술 분야 구인·공모 공고가 올라오는 사이트를 한 곳에 모았다.

이 파일이 "단일 기준"이다.
  - robots_check.py 는 여기서 SITES 를 읽어 robots.txt 판정을 돌린다.
  - export_sources.py 는 여기서 docs/sources.md(사람용 표)와 supabase/seed/crawl_sources.sql(DB 시드)을 만든다.
  - 새 소스를 붙일 때 crawl_<code>.py 의 SOURCE_CODE 는 반드시 여기의 code 와 같아야 한다.

각 항목의 뜻:
  code        crawl_sources.code (영문 소문자·숫자·밑줄). 크롤러 파일명 crawl_<code>.py 와 맞춘다.
  name        화면에 보이는 출처 이름.
  base_url    사이트 최상위 주소(robots.txt 를 여기서 읽는다).
  list_path   실제로 수집할 목록 페이지 경로. None 이면 아직 실측하지 못한 것 → 브라우저로 확인해 채운다.
  tier        1 통합 플랫폼(여러 기관 공고를 한 곳에)  2 중앙 공공기관  3 광역·기초 미술관/문화재단
              4 레지던시·비엔날레·사립미술관·전문분야  5 공모전 포털·공공 채용 API
  kind        채용 | 공모 | 채용+공모
  categories  아트잡스 표준 분야 코드(src/types/job.ts CATEGORIES.code). "all" 은 시각예술 전반.
  region      기관 소재 시·도. 통합 플랫폼은 "전국·온라인".
  fetch       html(정적 HTML) | api(공공데이터 API) | js(자바스크립트 렌더링 가능성 → 실측 필요)
  verified    True  검색 결과에서 목록 URL 을 직접 확인함
              False 기관은 확실하지만 목록 경로는 추정 → 실측 후 수정
  priority    1 먼저 붙일 것(공고량 많고 예술 특화)  2 다음  3 나중(공고량 적거나 경로 미정)
  note        수집 시 주의점(협의 필요, 유료 게재, 개인정보 게시판 제외 등).

원칙(바로쌤 계승):
  - robots.txt 판정이 '깨끗한 허용' 이거나 서면 협의가 있어야 is_active 를 켠다.
  - 구직자 개인정보가 담긴 인력풀·이력서·구직 게시판은 절대 대상이 아니다(여기에도 넣지 않는다).
  - 대형 취업포털(사람인·잡코리아·인크루트·인디드)은 약관상 자동수집 금지 → 대상에서 제외한다.
"""

SITES = [
    # ───────────────────────── 1. 통합 플랫폼 ─────────────────────────
    dict(code="artmore", name="아트모아(예술경영지원센터 예술 일자리 플랫폼)",
         base_url="https://www.artmore.kr",
         list_path="/sub/recruit/search_list.do?search_cd=JD&search_nm=%EB%AF%B8%EC%88%A0%EB%B6%84%EC%95%BC&search_val=13-17-28&listSize=50&page=1",
         tier=1, kind="채용", categories=["all"], region="전국·온라인", fetch="html", verified=True, priority=1,
         note="문체부·예술경영지원센터가 예술 분야 채용을 통합한 공식 플랫폼. 미술 분야 필터(search_val=13-17-28)로 검색. 공공 플랫폼이라 공식 협조 요청 여지가 큼."),
    dict(code="artnuri", name="아트누리(예술지원사업 통합 안내)",
         base_url="https://artnuri.or.kr", list_path="/crawler/info/search.do",
         tier=1, kind="공모", categories=["residency_open_call"], region="전국·온라인", fetch="js", verified=True, priority=1,
         note="문체부·한국문화예술위원회 운영. 120개 기관(공공기관 9·광역 17·기초 73 문화재단) 지원사업·공모 통합. 장르 '시각예술' 필터 확인 필요."),
    dict(code="momo365", name="모모365(문화사업지원플랫폼)",
         base_url="https://www.momo365.net", list_path="/Support?cd=support&ViewType=list",
         tier=1, kind="채용+공모", categories=["all"], region="전국·온라인", fetch="html", verified=True, priority=1,
         note="공모지원(/Support?cd=support)·공모전(/Support?cd=contest)·채용정보(/Recruit) 세 게시판. 민간 운영 → 이용약관 확인·서면 협의 권장. 연락처 culture.momo365@gmail.com"),
    dict(code="gokams_job", name="예술경영지원센터 채용정보",
         base_url="https://www.gokams.or.kr", list_path="/01_news/jobposting_list.aspx",
         tier=1, kind="채용", categories=["curation", "art_management"], region="전국·온라인", fetch="html", verified=True, priority=1,
         note="문화예술기관 채용정보 게시판. 일자리 정보 리스트(/01_news/job_list.aspx)도 함께 확인."),
    dict(code="kocaca", name="한국문화예술회관연합회(KoCACA) 채용공고",
         base_url="https://www.kocaca.or.kr", list_path="/myboard/myboard10",
         tier=1, kind="채용", categories=["curation", "art_management", "art_education"], region="전국·온라인", fetch="html", verified=True, priority=2,
         note="전국 문예회관 채용공고 모음. 구인게시판(/myboard/myboard14)도 있음. 공연 분야가 섞여 있어 분야 분류 필요."),
    dict(code="mcst_job", name="문화체육관광부 채용정보(소속·공공기관)",
         base_url="https://www.mcst.go.kr", list_path="/site/s_notice/notice/jobList.jsp?pTab=02",
         tier=1, kind="채용", categories=["curation", "art_management"], region="전국·온라인", fetch="html", verified=True, priority=2,
         note="문체부 소속기관·산하 공공기관 채용 모음(국립현대미술관·아시아문화전당 등 포함). 본부(pTab=01)는 제외."),
    dict(code="gojobs", name="나라일터(인사혁신처) 일반채용 모집공고",
         base_url="https://www.gojobs.go.kr", list_path="/apmList.do?menuNo=401",
         tier=1, kind="채용", categories=["curation"], region="전국·온라인", fetch="html", verified=True, priority=2,
         note="국가·지방 학예연구사(직) 임기제·경력채용이 여기에 뜬다. '학예' 검색어로 필터. 공공데이터포털 '인사혁신처_공공취업정보 조회' API(data.go.kr/data/15000485)로 대체 가능."),
    dict(code="curatorjob", name="큐레이터잡(큐레이터·학예사 구인정보)",
         base_url="https://www.xn--om2b25z4do96ac6a.com", list_path="/bbs/board.php?bo_table=guin",
         tier=1, kind="채용", categories=["curation", "art_management", "art_education"], region="전국·온라인", fetch="html", verified=True, priority=1,
         note="한글 도메인 큐레이터잡.com(그누보드). 구인 게시판만 대상. 구직(개인정보) 게시판은 절대 수집하지 않는다. 민간 운영 → 서면 협의."),
    dict(code="neolook", name="네오룩(비물질 아카이브) 모집·공모",
         base_url="https://neolook.com", list_path="/archives",
         tier=1, kind="채용+공모", categories=["all"], region="전국·온라인", fetch="html", verified=True, priority=2,
         note="전시·공모·레지던시·채용이 같은 archives 에 섞여 있어 제목 키워드(모집·공모·채용)로 걸러야 함. 게재가 유료(22만원)인 매체라 운영자 협의 필수."),
    dict(code="arthub", name="아트허브 아트잡·공모",
         base_url="https://www.arthub.co.kr", list_path="/m/board/job_list.html",
         tier=1, kind="채용+공모", categories=["all"], region="전국·온라인", fetch="html", verified=True, priority=2,
         note="아트잡(구인)·작가공모·레지던시 게시판 운영. PC 경로(sub04/sub05 board01)는 실측 후 확정."),
    dict(code="artmap", name="아트맵 공모·레지던시 소식",
         base_url="https://art-map.co.kr", list_path="/notice/list.php?b_id=002&showtype=3",
         tier=1, kind="공모", categories=["residency_open_call"], region="전국·온라인", fetch="html", verified=True, priority=2,
         note="b_id=002 레지던시. 공모 게시판 b_id 값은 실측. 문의 info@art-map.co.kr"),
    dict(code="daljin", name="김달진미술연구소(서울아트가이드) 구인구직",
         base_url="https://www.daljin.com", list_path=None,
         tier=1, kind="채용", categories=["all"], region="전국·온라인", fetch="html", verified=False, priority=3,
         note="구인 게시판 경로(index.php?WS=…) 실측 필요. 구직 글은 제외."),
    dict(code="art1", name="아트원 구인/구직 게시판",
         base_url="https://www.art1.com", list_path="/bbs/",
         tier=1, kind="채용", categories=["all"], region="전국·온라인", fetch="html", verified=False, priority=3,
         note="게시판 분류 파라미터 실측 필요. 구직 글은 제외."),
    dict(code="artnet", name="아트넷 채용정보·공모전",
         base_url="http://artnet.kr", list_path="/p/recruit",
         tier=1, kind="채용+공모", categories=["all"], region="전국·온라인", fetch="html", verified=True, priority=3,
         note="공모전은 /p/competition. https 지원 여부 확인."),
    dict(code="artistmap", name="아티스트맵 일자리 정보",
         base_url="https://artistmap.kr", list_path="/board/list/code/job",
         tier=1, kind="채용", categories=["all"], region="전국·온라인", fetch="html", verified=False, priority=3,
         note="상세 URL(/board/view/id/…/code/job)만 확인됨. 목록 경로 실측."),
    dict(code="artculture", name="아트앤컬처 문화예술신문 공모",
         base_url="https://art-culture.co.kr", list_path="/magazine_contest",
         tier=1, kind="공모", categories=["residency_open_call"], region="전국·온라인", fetch="html", verified=True, priority=3,
         note="레지던시·공모 소식 재게시. 원문 기관 링크가 있으면 원문을 source_url 로."),
    dict(code="kfaa", name="한국미술협회 미술계 소식",
         base_url="https://kfaa.or.kr", list_path="/bbs/?so_table=art_news01",
         tier=1, kind="공모", categories=["all"], region="전국·온라인", fetch="html", verified=True, priority=3,
         note="공모·전시 소식 게시판. 채용 비중은 낮음."),
    dict(code="seoul_culture", name="서울문화포털 채용공고",
         base_url="https://culture.seoul.go.kr", list_path="/culture/bbs/B0000002/list.do?menuNo=200052",
         tier=1, kind="채용", categories=["all"], region="서울", fetch="html", verified=True, priority=2,
         note="서울시 문화기관(시립미술관·박물관·문화재단 등) 채용 모음."),

    # ───────────────────────── 2. 중앙 공공기관 ─────────────────────────
    dict(code="arko", name="한국문화예술위원회(ARKO) 채용",
         base_url="https://arko.recruiton.kr", list_path="/recruit/gongo/gongo_list.asp",
         tier=2, kind="채용", categories=["art_management", "curation"], region="전남", fetch="html", verified=True, priority=2,
         note="본 사이트 채용모집 게시판은 www.arko.or.kr/board/list/4054(추정). 지원사업 공모는 아트누리로 통합됨."),
    dict(code="mmca", name="국립현대미술관 채용",
         base_url="https://www.mmca.go.kr", list_path="/pr/employmentList.do",
         tier=2, kind="채용+공모", categories=["curation", "art_education", "residency_open_call"], region="서울", fetch="html", verified=True, priority=1,
         note="학예연구직·기간제·인턴 채용. 고양·창동 레지던시 입주작가 공모는 공지사항(/pr/noticeList.do 추정)에 뜸."),
    dict(code="sema", name="서울시립미술관 채용시험",
         base_url="https://sema.seoul.go.kr", list_path="/kr/bbs/611389/getBbsList",
         tier=2, kind="채용+공모", categories=["curation", "art_education", "photography", "media_art"], region="서울", fetch="html", verified=True, priority=1,
         note="채용시험(611389)·공지사항/공고·공모(610221) 두 게시판. 사진미술관·미디어시티비엔날레·난지창작스튜디오 공모 포함."),
    dict(code="acc", name="국립아시아문화전당 채용공고",
         base_url="https://www.acc.go.kr", list_path="/main/board/board.do?PID=0702",
         tier=2, kind="채용+공모", categories=["curation", "media_art", "residency_open_call"], region="광주", fetch="html", verified=True, priority=2,
         note="ACC_R 레지던시·아시아창작스튜디오 공모는 공지 게시판. 재단 채용은 recruit.incruit.com/accf(인크루트 채용관 → 수집 대상 아님)."),
    dict(code="kcdf", name="한국공예·디자인문화진흥원 채용공고",
         base_url="https://www.kcdf.or.kr", list_path="/brd/board/342/L/menu/288",
         tier=2, kind="채용+공모", categories=["craft"], region="서울", fetch="html", verified=True, priority=1,
         note="채용공고(342/288)·사업공모(/brd/board/337/L/menu/284). 공예청년인턴십 등 공예 분야 핵심 소스."),
    dict(code="arte", name="한국문화예술교육진흥원 채용공고",
         base_url="https://arte.or.kr", list_path="/notice/job/notice/Job_BoardList.do",
         tier=2, kind="채용+공모", categories=["art_education"], region="서울", fetch="html", verified=True, priority=1,
         note="직원 채용 + 예술강사 모집 공고. 학교 예술강사 지원사업은 aschool.arte.or.kr 별도."),
    dict(code="kawf", name="한국예술인복지재단 공지사항",
         base_url="https://www.kawf.kr", list_path="/notice/sub01List.do",
         tier=2, kind="채용+공모", categories=["all"], region="서울", fetch="html", verified=False, priority=2,
         note="상세는 /notice/sub01View.do?selIdx=… 확인됨. 예술인파견지원(예술로) 등 예술인 대상 공모."),
    dict(code="museum_go", name="국립중앙박물관 채용 안내",
         base_url="https://www.museum.go.kr", list_path="/MUSEUM/contents/M0701030000.do?catCustomType=post&catId=54",
         tier=2, kind="채용", categories=["curation"], region="서울", fetch="html", verified=True, priority=3,
         note="학예연구원 채용(소속 지방박물관 포함). 미술 외 고고·역사 공고가 섞여 제목 필터 필요."),
    dict(code="craftmuseum", name="서울공예박물관 채용",
         base_url="https://craftmuseum.seoul.go.kr", list_path="/introduce/recruit",
         tier=2, kind="채용", categories=["craft", "curation"], region="서울", fetch="html", verified=False, priority=2,
         note="상세 /introduce/recruit_view/NTT_… 확인됨. 목록 경로 실측."),
    dict(code="museum_assoc", name="한국박물관협회 채용정보",
         base_url="https://museum.or.kr", list_path=None,
         tier=2, kind="채용", categories=["curation"], region="서울", fetch="html", verified=False, priority=3,
         note="회원 박물관·미술관 구인 게시판 경로 실측 필요."),
    dict(code="artmuseums", name="한국사립미술관협회",
         base_url="https://artmuseums.kr", list_path=None,
         tier=2, kind="채용+공모", categories=["curation", "art_education"], region="서울", fetch="html", verified=False, priority=3,
         note="사립미술관 채용·공모 게시판 유무부터 확인."),
    dict(code="galleries", name="한국화랑협회",
         base_url="https://www.koreagalleries.or.kr", list_path=None,
         tier=2, kind="채용", categories=["art_management"], region="서울", fetch="html", verified=False, priority=3,
         note="갤러리 채용 게시판 유무 확인. 키아프(kiaf.org) 채용도 여기 계열."),

    # ───────────────────────── 3. 광역 미술관 ─────────────────────────
    dict(code="busan_art", name="부산시립미술관 고시공고",
         base_url="https://art.busan.go.kr", list_path="/anucmt/list.nm",
         tier=3, kind="채용+공모", categories=["curation", "art_education"], region="부산", fetch="html", verified=False, priority=2,
         note="상세 /anucmt/view.nm 확인됨. 부산시 채용공고(busan.go.kr/nbincruit)에도 동시 게재."),
    dict(code="daegu_art", name="대구미술관",
         base_url="https://daeguartmuseum.or.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["curation", "art_education"], region="대구", fetch="html", verified=False, priority=2,
         note="채용·공고 게시판 경로 실측."),
    dict(code="gwangju_art", name="광주시립미술관",
         base_url="https://artmuse.gwangju.go.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["curation", "residency_open_call"], region="광주", fetch="html", verified=False, priority=2,
         note="북구 창작스튜디오 입주작가 공모 포함. 경로 실측."),
    dict(code="daejeon_art", name="대전시립미술관",
         base_url="https://www.daejeon.go.kr", list_path="/dma/DmaBoardList.do?menuSeq=6098",
         tier=3, kind="채용+공모", categories=["curation", "art_education"], region="대전", fetch="html", verified=False, priority=2,
         note="상세 /dma/DmaBoardView.do?menuSeq=6098 확인됨. 대전시 포털 하위라 robots 는 daejeon.go.kr 기준."),
    dict(code="ulsan_art", name="울산시립미술관",
         base_url="https://www.ulsan.go.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["curation", "media_art"], region="울산", fetch="html", verified=False, priority=3,
         note="울산시 포털 하위(/s/uam). 경로 실측."),
    dict(code="gmoma", name="경기도미술관",
         base_url="https://gmoma.ggcf.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["curation", "art_education"], region="경기", fetch="html", verified=False, priority=2,
         note="경기문화재단 계열. 채용은 재단 통합 채용(ggcf.saramin.co.kr)로 빠질 수 있음."),
    dict(code="njp", name="백남준아트센터",
         base_url="https://njp.ggcf.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["media_art", "curation"], region="경기", fetch="html", verified=False, priority=2,
         note="미디어아트 핵심 기관. 공지·공모 경로 실측."),
    dict(code="gyeongnam_art", name="경남도립미술관",
         base_url="https://www.gyeongnam.go.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["curation"], region="경남", fetch="html", verified=False, priority=3,
         note="경남도 포털 하위(/gam). 경로 실측."),
    dict(code="jeonbuk_art", name="전북도립미술관",
         base_url="https://www.jma.go.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["curation", "residency_open_call"], region="전북", fetch="html", verified=False, priority=3,
         note="창작스튜디오 공모 포함. 경로 실측."),
    dict(code="jeonnam_art", name="전남도립미술관",
         base_url="https://jnam.jeonnam.go.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["curation"], region="전남", fetch="html", verified=False, priority=3,
         note="경로 실측."),
    dict(code="jeju_art", name="제주도립미술관",
         base_url="https://www.jeju.go.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["curation"], region="제주", fetch="html", verified=False, priority=3,
         note="제주도 포털 하위(/jmoa). 경로 실측."),
    dict(code="suwon_art", name="수원시립미술관",
         base_url="https://suma.suwon.go.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["curation", "art_education"], region="경기", fetch="html", verified=False, priority=3,
         note="경로 실측."),
    dict(code="cheongju_art", name="청주시립미술관",
         base_url="https://cmoa.cheongju.go.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["curation"], region="충북", fetch="html", verified=False, priority=3,
         note="경로 실측."),

    # ───────────────────────── 3. 광역 문화재단(17) ─────────────────────────
    dict(code="sfac", name="서울문화재단 채용공고",
         base_url="https://www.sfac.or.kr", list_path="/opensquare/notice/recruit_list.do",
         tier=3, kind="채용+공모", categories=["all"], region="서울", fetch="html", verified=True, priority=1,
         note="입주작가 공모는 /participation/participation/artspace_movein.do (금천예술공장·서울예술창작센터 등). 직원 공채는 recruit.sfac.or.kr."),
    dict(code="ggcf", name="경기문화재단",
         base_url="https://www.ggcf.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["all"], region="경기", fetch="html", verified=False, priority=2,
         note="채용은 ggcf.saramin.co.kr(사람인 채용관 → 수집 대상 아님). 공모는 경기예술인지원센터(artist.ggcf.kr) 확인."),
    dict(code="ifac", name="인천문화재단",
         base_url="https://www.ifac.or.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["all"], region="인천", fetch="html", verified=False, priority=2,
         note="채용관 ifac.incruit.com. 인천아트플랫폼 레지던시는 별도(inartplatform)."),
    dict(code="bscf", name="부산문화재단",
         base_url="https://www.bscf.or.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["all"], region="부산", fetch="html", verified=False, priority=2,
         note="채용관 busancf.saramin.co.kr. 홍티아트센터 레지던시 공모 포함."),
    dict(code="dgfac", name="대구문화예술진흥원",
         base_url="https://www.dgfac.or.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["all"], region="대구", fetch="html", verified=False, priority=3,
         note="도메인·경로 실측(대구예술발전소는 별도 daeguartfactory)."),
    dict(code="gjcf", name="광주문화재단 채용공고",
         base_url="https://www.gjcf.or.kr", list_path="/cf/news/hire.do",
         tier=3, kind="채용+공모", categories=["all"], region="광주", fetch="html", verified=True, priority=2,
         note="열린광장 > 채용공고."),
    dict(code="dcaf", name="대전문화재단",
         base_url="https://www.dcaf.or.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["all"], region="대전", fetch="html", verified=False, priority=3,
         note="경로 실측."),
    dict(code="uctf", name="울산문화관광재단",
         base_url="https://www.uctf.or.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["all"], region="울산", fetch="html", verified=False, priority=3,
         note="채용관 uctf.saramin.co.kr / recruit.incruit.com/uctf. 본 사이트 공고 경로 실측."),
    dict(code="sjcf", name="세종시문화관광재단",
         base_url="https://www.sjcf.or.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["all"], region="세종", fetch="html", verified=False, priority=3,
         note="경로 실측."),
    dict(code="gwcf", name="강원문화재단",
         base_url="https://www.gwcf.or.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["all"], region="강원", fetch="html", verified=False, priority=3,
         note="경로 실측. 강원국제트리엔날레 공모 포함 가능."),
    dict(code="cbfc", name="충북문화재단",
         base_url="https://www.cbfc.or.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["all"], region="충북", fetch="html", verified=False, priority=3,
         note="경로 실측."),
    dict(code="ctcf", name="충남문화관광재단",
         base_url="https://www.ctcf.or.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["all"], region="충남", fetch="html", verified=False, priority=3,
         note="경로 실측."),
    dict(code="jbct", name="전북문화관광재단",
         base_url="https://www.jbct.or.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["all"], region="전북", fetch="html", verified=False, priority=3,
         note="경로 실측."),
    dict(code="jncf", name="전남문화재단",
         base_url="https://www.jncf.or.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["all"], region="전남", fetch="html", verified=False, priority=3,
         note="채용관 jeonnam.saramin.co.kr. 본 사이트 경로 실측."),
    dict(code="gacf", name="경북문화재단",
         base_url="http://www.gacf.kr", list_path=None,
         tier=3, kind="채용+공모", categories=["all"], region="경북", fetch="html", verified=False, priority=3,
         note="https 지원 여부·경로 실측."),
    dict(code="gcaf", name="경남문화예술진흥원 공고",
         base_url="https://www.gcaf.or.kr", list_path="/bbs/board.php?bo_table=sub4_1",
         tier=3, kind="채용+공모", categories=["all"], region="경남", fetch="html", verified=True, priority=2,
         note="그누보드 공고 게시판(sub4_1). 마산현대미술관 레지던시 공모 등."),
    dict(code="jfac", name="제주문화예술재단 채용공고",
         base_url="http://www.jcaf.or.kr", list_path="/contents/index.php?mid=070102",
         tier=3, kind="채용+공모", categories=["all"], region="제주", fetch="html", verified=True, priority=2,
         note="채용관 recruit.incruit.com/jfac. 레지던시 입주작가 통합공모 매년 게시."),

    # ───────────────────────── 4. 레지던시·비엔날레·사립·전문분야 ─────────────────────────
    dict(code="inartplatform", name="인천아트플랫폼 공지사항",
         base_url="https://inartplatform.kr", list_path="/notice",
         tier=4, kind="채용+공모", categories=["residency_open_call", "curation"], region="인천", fetch="html", verified=True, priority=2,
         note="레지던시 입주작가 공모·인턴 채용."),
    dict(code="daeguartfactory", name="대구예술발전소 공지사항",
         base_url="https://www.daeguartfactory.kr", list_path="/front/board/list.php?code=notice",
         tier=4, kind="채용+공모", categories=["residency_open_call"], region="대구", fetch="html", verified=False, priority=2,
         note="상세 /front/board/view.php?code=notice&no=… 확인됨. 매년 12월 레지던시 입주작가 모집."),
    dict(code="nabi", name="아트센터 나비",
         base_url="https://www.nabi.or.kr", list_path="/page/board_list.php?brd_id=project",
         tier=4, kind="채용+공모", categories=["media_art", "residency_open_call"], region="서울", fetch="html", verified=False, priority=3,
         note="상세 /page/board_view.php?brd_id=project 확인됨. 나비 아티스트 레지던시(미디어아트)."),
    dict(code="namjunepaik", name="백남준문화재단 미디어아트 공모",
         base_url="https://namjunepaik.org", list_path=None,
         tier=4, kind="공모", categories=["media_art"], region="전국·온라인", fetch="html", verified=False, priority=3,
         note="연 1회 미디어아트 공모전(39세 이하). 상세 /media-art-competition-2025 확인됨."),
    dict(code="gwangjubiennale", name="광주비엔날레",
         base_url="https://www.gwangjubiennale.org", list_path=None,
         tier=4, kind="채용+공모", categories=["curation", "art_management"], region="광주", fetch="html", verified=False, priority=2,
         note="채용·전시기획자양성과정 모집. 공지 경로 실측."),
    dict(code="busanbiennale", name="부산비엔날레 채용공고",
         base_url="http://www.busanbiennale.org", list_path="/BBOCkr/index.php?pCode=gongo&mode=list",
         tier=4, kind="채용", categories=["curation", "art_management"], region="부산", fetch="html", verified=True, priority=2,
         note="https 지원 여부 확인."),
    dict(code="changwon_biennale", name="창원조각비엔날레(창원문화재단)",
         base_url="https://www.changwonbiennale.or.kr", list_path=None,
         tier=4, kind="채용+공모", categories=["sculpture_installation", "curation"], region="경남", fetch="html", verified=False, priority=3,
         note="조각 분야 핵심 행사. 조직위 채용·참여작가 공모. 경로 실측."),
    dict(code="okcj", name="청주공예비엔날레",
         base_url="https://www.okcj.org", list_path=None,
         tier=4, kind="채용+공모", categories=["craft", "curation"], region="충북", fetch="html", verified=False, priority=3,
         note="조직위 기간제 채용·공예 공모. 경로 실측."),
    dict(code="leeum", name="리움미술관 공지",
         base_url="https://www.leeumhoam.org", list_path="/leeum/info/notice",
         tier=4, kind="채용", categories=["curation", "art_education"], region="서울", fetch="js", verified=True, priority=3,
         note="공지에 채용이 섞여 있음. 자바스크립트 렌더링 여부 실측. 사립 → 서면 협의."),
    dict(code="museumhanmi", name="뮤지엄한미 공모(MH Talent Portfolio)",
         base_url="https://museumhanmi.or.kr", list_path=None,
         tier=4, kind="채용+공모", categories=["photography"], region="서울", fetch="html", verified=False, priority=3,
         note="사진 분야 작가 포트폴리오 공모. 공지 경로 실측."),
    dict(code="goeun", name="고은사진미술관",
         base_url="https://www.goeunmuseum.kr", list_path=None,
         tier=4, kind="채용+공모", categories=["photography"], region="부산", fetch="html", verified=False, priority=3,
         note="사진 분야. 공지 경로 실측."),
    dict(code="artsonje", name="아트선재센터",
         base_url="https://artsonje.org", list_path=None,
         tier=4, kind="채용", categories=["curation"], region="서울", fetch="html", verified=False, priority=3,
         note="사립. 채용 공지 경로·협의."),
    dict(code="ilmin", name="일민미술관",
         base_url="https://ilmin.org", list_path=None,
         tier=4, kind="채용", categories=["curation"], region="서울", fetch="html", verified=False, priority=3,
         note="사립. 채용 공지 경로·협의."),
    dict(code="apma", name="아모레퍼시픽미술관",
         base_url="https://apma.amorepacific.com", list_path=None,
         tier=4, kind="채용", categories=["curation"], region="서울", fetch="html", verified=False, priority=3,
         note="사립. 채용은 그룹 채용사이트로 갈 가능성 → 확인."),
    dict(code="songeun", name="송은",
         base_url="https://www.songeun.or.kr", list_path=None,
         tier=4, kind="채용+공모", categories=["curation", "residency_open_call"], region="서울", fetch="html", verified=False, priority=3,
         note="송은미술대상 공모·채용. 경로 실측."),
    dict(code="kiaf", name="키아프 서울(한국화랑협회)",
         base_url="https://kiaf.org", list_path=None,
         tier=4, kind="채용", categories=["art_management"], region="서울", fetch="html", verified=False, priority=3,
         note="아트페어 스태프 채용. 경로 실측."),

    # ───────────────────────── 5. 공모전 포털·공공 채용 API ─────────────────────────
    dict(code="alio_api", name="잡알리오 공공기관 채용정보(공공데이터 API)",
         base_url="https://job.alio.go.kr", list_path=None,
         tier=5, kind="채용", categories=["curation", "art_management", "art_education"], region="전국·온라인", fetch="api", verified=True, priority=2,
         note="공공데이터포털 '재정경제부_공공기관 채용정보 조회서비스'(data.go.kr/data/15125273) 인증키 신청 후 사용. 예술경영지원센터·문화예술위원회·ACC재단·KCDF·문화예술교육진흥원·국립박물관문화재단 등 기관코드로 필터."),
    dict(code="work24_api", name="고용24(워크넷) 채용정보 API",
         base_url="https://www.work24.go.kr", list_path=None,
         tier=5, kind="채용", categories=["all"], region="전국·온라인", fetch="api", verified=True, priority=3,
         note="공공데이터포털 워크넷 채용정보 API. 직종코드(문화·예술·디자인)로 필터. 공고량은 많으나 예술 특화도는 낮음."),
    dict(code="contestkorea", name="콘테스트코리아 미술·디자인 공모전",
         base_url="https://www.contestkorea.com", list_path="/sub/list.php?int_gbn=1&Txt_bcode=030610001",
         tier=5, kind="공모", categories=["painting", "print_drawing", "media_art", "photography"], region="전국·온라인", fetch="html", verified=True, priority=3,
         note="미술·디자인·웹툰 분류. 디자인·웹툰은 제목 키워드로 제외."),
    dict(code="wevity", name="위비티 예체능·미술 공모전",
         base_url="https://www.wevity.com", list_path=None,
         tier=5, kind="공모", categories=["painting", "photography", "media_art"], region="전국·온라인", fetch="html", verified=False, priority=3,
         note="분야 필터 파라미터 실측. 민간 → 협의."),
    dict(code="thinkcontest", name="씽굿 공모전",
         base_url="https://www.thinkcontest.com", list_path="/Contest/CateField.html?c=8",
         tier=5, kind="공모", categories=["painting", "photography", "media_art"], region="전국·온라인", fetch="html", verified=False, priority=3,
         note="분야 코드(c=8)가 미술인지 실측. 민간 → 협의."),
]

# 대상에서 제외한 사이트 — 이유와 함께 기록해 두어 다시 검토하지 않게 한다.
EXCLUDED = [
    ("사람인·잡코리아·인크루트·인디드·캐치·자소설닷컴", "대형 취업포털. 이용약관에서 자동수집 금지, robots 차단. 기관별 채용관(xxx.saramin.co.kr 등)도 동일."),
    ("기관별 인크루트/사람인 채용관(recruit.incruit.com/*, *.saramin.co.kr)", "위와 같음. 기관 본 사이트 공고 게시판을 대신 수집한다."),
    ("네이버 카페·오픈채팅(학예사 준비 카페 등)", "로그인 필요 + 개인 게시물. 수집 불가."),
    ("구직·인력풀·이력서 게시판 전부", "구직자 개인정보. 어떤 사이트든 구인 게시판만 대상."),
    ("예술의전당·국립극장 등 공연예술 전용 기관", "아트잡스 분야(시각예술) 밖. 문예회관 통합(kocaca)에서 시각예술 공고만 거른다."),
]


def by_code(code):
    return next((s for s in SITES if s["code"] == code), None)


def robots_targets():
    """robots_check.py 가 쓰는 (code, name, base, list_path) 튜플. 경로 미정은 '/' 로 판정한다."""
    return [(s["code"], s["name"], s["base_url"], s["list_path"] or "/") for s in SITES]


if __name__ == "__main__":
    codes = [s["code"] for s in SITES]
    assert len(codes) == len(set(codes)), "code 중복"
    tiers = {}
    for s in SITES:
        tiers[s["tier"]] = tiers.get(s["tier"], 0) + 1
    print(f"사이트 {len(SITES)}곳 | 단계별 {dict(sorted(tiers.items()))} | 목록경로 확정 {sum(1 for s in SITES if s['list_path'])}곳")
