-- crawl_sources 시드 — scripts/crawler/sources.py 에서 자동 생성. 손으로 고치지 말 것.
-- 모든 행은 is_active=false, robots_status='unchecked' 로 들어간다. robots 판정·협의 후 개별 갱신한다.
-- 이미 있는 code 는 name/base_url/list_path/note 만 갱신하고 robots_status·is_active 는 건드리지 않는다.

insert into crawl_sources (code, name, base_url, list_path, robots_status, is_active, note) values
  ('artmore', '아트모아(예술경영지원센터 예술 일자리 플랫폼)', 'https://www.artmore.kr', '/sub/recruit/search_list.do?search_cd=JD&search_nm=%EB%AF%B8%EC%88%A0%EB%B6%84%EC%95%BC&search_val=13-17-28&listSize=50&page=1', 'unchecked', false, '[1단계/채용/우선1/all/전국·온라인] 문체부·예술경영지원센터가 예술 분야 채용을 통합한 공식 플랫폼. 미술 분야 필터(search_val=13-17-28)로 검색. 공공 플랫폼이라 공식 협조 요청 여지가 큼.'),
  ('artnuri', '아트누리(예술지원사업 통합 안내)', 'https://artnuri.or.kr', '/crawler/info/search.do', 'unchecked', false, '[1단계/공모/우선1/residency_open_call/전국·온라인] 문체부·한국문화예술위원회 운영. 120개 기관(공공기관 9·광역 17·기초 73 문화재단) 지원사업·공모 통합. 장르 ''시각예술'' 필터 확인 필요.'),
  ('momo365', '모모365(문화사업지원플랫폼)', 'https://www.momo365.net', '/Support?cd=support&ViewType=list', 'unchecked', false, '[1단계/채용+공모/우선1/all/전국·온라인] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 공모지원(/Support?cd=support)·공모전(/Support?cd=contest)·채용정보(/Recruit) 세 게시판. 민간 운영 → 이용약관 확인·서면 협의 권장. 연락처 culture.momo365@gmail.com'),
  ('gokams_job', '예술경영지원센터 채용정보', 'https://www.gokams.or.kr', '/01_news/jobposting_list.aspx', 'unchecked', false, '[1단계/채용/우선1/curation·art_management/전국·온라인] 문화예술기관 채용정보 게시판. 일자리 정보 리스트(/01_news/job_list.aspx)도 함께 확인.'),
  ('kocaca', '한국문화예술회관연합회(KoCACA) 채용공고', 'https://www.kocaca.or.kr', '/myboard/myboard10', 'unchecked', false, '[1단계/채용/우선2/curation·art_management·art_education/전국·온라인] 전국 문예회관 채용공고 모음. 구인게시판(/myboard/myboard14)도 있음. 공연 분야가 섞여 있어 분야 분류 필요.'),
  ('mcst_job', '문화체육관광부 채용정보(소속·공공기관)', 'https://www.mcst.go.kr', '/site/s_notice/notice/jobList.jsp?pTab=02', 'unchecked', false, '[1단계/채용/우선2/curation·art_management/전국·온라인] 문체부 소속기관·산하 공공기관 채용 모음(국립현대미술관·아시아문화전당 등 포함). 본부(pTab=01)는 제외.'),
  ('gojobs', '나라일터(인사혁신처) 일반채용 모집공고', 'https://www.gojobs.go.kr', '/apmList.do?menuNo=401', 'unchecked', false, '[1단계/채용/우선2/curation/전국·온라인] 국가·지방 학예연구사(직) 임기제·경력채용이 여기에 뜬다. ''학예'' 검색어로 필터. 공공데이터포털 ''인사혁신처_공공취업정보 조회'' API(data.go.kr/data/15000485)로 대체 가능.'),
  ('curatorjob', '큐레이터잡(큐레이터·학예사 구인정보)', 'https://www.xn--om2b25z4do96ac6a.com', '/bbs/board.php?bo_table=guin', 'unchecked', false, '[1단계/채용/우선1/curation·art_management·art_education/전국·온라인] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 한글 도메인 큐레이터잡.com(그누보드). 구인 게시판만 대상. 구직(개인정보) 게시판은 절대 수집하지 않는다. 민간 운영 → 서면 협의.'),
  ('neolook', '네오룩(비물질 아카이브) 모집·공모', 'https://neolook.com', '/archives', 'unchecked', false, '[1단계/채용+공모/우선2/all/전국·온라인] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 전시·공모·레지던시·채용이 같은 archives 에 섞여 있어 제목 키워드(모집·공모·채용)로 걸러야 함. 게재가 유료(22만원)인 매체라 운영자 협의 필수.'),
  ('arthub', '아트허브 아트잡·공모', 'https://www.arthub.co.kr', '/m/board/job_list.html', 'unchecked', false, '[1단계/채용+공모/우선2/all/전국·온라인] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 아트잡(구인)·작가공모·레지던시 게시판 운영. PC 경로(sub04/sub05 board01)는 실측 후 확정.'),
  ('artmap', '아트맵 공모·레지던시 소식', 'https://art-map.co.kr', '/notice/list.php?b_id=002&showtype=3', 'unchecked', false, '[1단계/공모/우선2/residency_open_call/전국·온라인] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. b_id=002 레지던시. 공모 게시판 b_id 값은 실측. 문의 info@art-map.co.kr'),
  ('daljin', '김달진미술연구소(서울아트가이드) 구인구직', 'https://www.daljin.com', null, 'unchecked', false, '[1단계/채용/우선3/all/전국·온라인] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 구인 게시판 경로(index.php?WS=…) 실측 필요. 구직 글은 제외.'),
  ('art1', '아트원 구인/구직 게시판', 'https://www.art1.com', '/bbs/', 'unchecked', false, '[1단계/채용/우선3/all/전국·온라인] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 게시판 분류 파라미터 실측 필요. 구직 글은 제외.'),
  ('artnet', '아트넷 채용정보·공모전', 'http://artnet.kr', '/p/recruit', 'unchecked', false, '[1단계/채용+공모/우선3/all/전국·온라인] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 공모전은 /p/competition. https 지원 여부 확인.'),
  ('artistmap', '아티스트맵 일자리 정보', 'https://artistmap.kr', '/board/list/code/job', 'unchecked', false, '[1단계/채용/우선3/all/전국·온라인] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 상세 URL(/board/view/id/…/code/job)만 확인됨. 목록 경로 실측.'),
  ('artculture', '아트앤컬처 문화예술신문 공모', 'https://art-culture.co.kr', '/magazine_contest', 'unchecked', false, '[1단계/공모/우선3/residency_open_call/전국·온라인] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 레지던시·공모 소식 재게시. 원문 기관 링크가 있으면 원문을 source_url 로.'),
  ('kfaa', '한국미술협회 미술계 소식', 'https://kfaa.or.kr', '/bbs/?so_table=art_news01', 'unchecked', false, '[1단계/공모/우선3/all/전국·온라인] 공모·전시 소식 게시판. 채용 비중은 낮음.'),
  ('seoul_culture', '서울문화포털 채용공고', 'https://culture.seoul.go.kr', '/culture/bbs/B0000002/list.do?menuNo=200052', 'unchecked', false, '[1단계/채용/우선2/all/서울] 서울시 문화기관(시립미술관·박물관·문화재단 등) 채용 모음.'),
  ('arko', '한국문화예술위원회(ARKO) 채용', 'https://www.arko.or.kr', null, 'unchecked', false, '[2단계/채용/우선2/art_management·curation/전남] 채용관(arko.recruiton.kr)은 목록 주소가 welcome 페이지로 넘어가 수집 불가 → 본 사이트 채용모집 게시판(board/list/4054 추정) 주소 실측. 지원사업 공모는 아트누리로 통합됨.'),
  ('mmca', '국립현대미술관 채용', 'https://www.mmca.go.kr', '/pr/employmentList.do', 'unchecked', false, '[2단계/채용+공모/우선1/curation·art_education·residency_open_call/서울] 학예연구직·기간제·인턴 채용. 고양·창동 레지던시 입주작가 공모는 공지사항(/pr/noticeList.do 추정)에 뜸.'),
  ('sema', '서울시립미술관 채용시험', 'https://sema.seoul.go.kr', '/kr/bbs/611389/getBbsList', 'unchecked', false, '[2단계/채용+공모/우선1/curation·art_education·photography·media_art/서울] 채용시험(611389)·공지사항/공고·공모(610221) 두 게시판. 사진미술관·미디어시티비엔날레·난지창작스튜디오 공모 포함.'),
  ('acc', '국립아시아문화전당 채용공고', 'https://www.acc.go.kr', '/main/board/board.do?PID=0702', 'unchecked', false, '[2단계/채용+공모/우선2/curation·media_art·residency_open_call/광주] ACC_R 레지던시·아시아창작스튜디오 공모는 공지 게시판. 재단 채용은 recruit.incruit.com/accf(인크루트 채용관 → 수집 대상 아님).'),
  ('kcdf', '한국공예·디자인문화진흥원 채용공고', 'https://www.kcdf.or.kr', '/brd/board/342/L/menu/288', 'unchecked', false, '[2단계/채용+공모/우선1/craft/서울] 채용공고(342/288)·사업공모(/brd/board/337/L/menu/284). 공예청년인턴십 등 공예 분야 핵심 소스.'),
  ('arte', '한국문화예술교육진흥원 채용공고', 'https://arte.or.kr', '/notice/job/notice/Job_BoardList.do', 'unchecked', false, '[2단계/채용+공모/우선1/art_education/서울] 직원 채용 + 예술강사 모집 공고. 학교 예술강사 지원사업은 aschool.arte.or.kr 별도.'),
  ('kawf', '한국예술인복지재단 공지사항', 'https://www.kawf.kr', null, 'unchecked', false, '[2단계/채용+공모/우선2/all/서울] 추정 목록 주소(/notice/sub01List.do)는 404. 상세는 /notice/sub01View.do?selIdx=… 확인됨 → 공지 목록 주소 실측. 예술인파견지원(예술로) 등 예술인 대상 공모.'),
  ('museum_go', '국립중앙박물관 채용 안내', 'https://www.museum.go.kr', '/MUSEUM/contents/M0701030000.do?catCustomType=post&catId=54', 'unchecked', false, '[2단계/채용/우선3/curation/서울] 학예연구원 채용(소속 지방박물관 포함). 미술 외 고고·역사 공고가 섞여 제목 필터 필요.'),
  ('craftmuseum', '서울공예박물관 채용', 'https://craftmuseum.seoul.go.kr', null, 'unchecked', false, '[2단계/채용/우선2/craft·curation/서울] 추정 목록 주소(/introduce/recruit)는 404. 상세 /introduce/recruit_view/NTT_… 확인됨 → 목록 주소 실측.'),
  ('museum_assoc', '한국박물관협회 채용정보', 'https://museum.or.kr', null, 'unchecked', false, '[2단계/채용/우선3/curation/서울] 회원 박물관·미술관 구인 게시판 경로 실측 필요.'),
  ('artmuseums', '한국사립미술관협회', 'https://artmuseums.kr', null, 'unchecked', false, '[2단계/채용+공모/우선3/curation·art_education/서울] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 사립미술관 채용·공모 게시판 유무부터 확인.'),
  ('galleries', '한국화랑협회', 'https://www.koreagalleries.or.kr', null, 'unchecked', false, '[2단계/채용/우선3/art_management/서울] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 갤러리 채용 게시판 유무 확인. 키아프(kiaf.org) 채용도 여기 계열.'),
  ('busan_art', '부산시립미술관 고시공고', 'https://art.busan.go.kr', '/anucmt/list.nm', 'unchecked', false, '[3단계/채용+공모/우선2/curation·art_education/부산] 상세 /anucmt/view.nm 확인됨. 부산시 채용공고(busan.go.kr/nbincruit)에도 동시 게재.'),
  ('daegu_art', '대구미술관', 'https://daeguartmuseum.or.kr', null, 'unchecked', false, '[3단계/채용+공모/우선2/curation·art_education/대구] 채용·공고 게시판 경로 실측.'),
  ('gwangju_art', '광주시립미술관', 'https://artmuse.gwangju.go.kr', null, 'unchecked', false, '[3단계/채용+공모/우선2/curation·residency_open_call/광주] 북구 창작스튜디오 입주작가 공모 포함. 경로 실측.'),
  ('daejeon_art', '대전시립미술관', 'https://www.daejeon.go.kr', '/dma/DmaBoardList.do?menuSeq=6098', 'unchecked', false, '[3단계/채용+공모/우선2/curation·art_education/대전] 상세 /dma/DmaBoardView.do?menuSeq=6098 확인됨. 대전시 포털 하위라 robots 는 daejeon.go.kr 기준.'),
  ('ulsan_art', '울산시립미술관', 'https://www.ulsan.go.kr', null, 'unchecked', false, '[3단계/채용+공모/우선3/curation·media_art/울산] 울산시 포털 하위(/s/uam). 경로 실측.'),
  ('gmoma', '경기도미술관', 'https://gmoma.ggcf.kr', null, 'unchecked', false, '[3단계/채용+공모/우선2/curation·art_education/경기] 경기문화재단 계열. 채용은 재단 통합 채용(ggcf.saramin.co.kr)로 빠질 수 있음.'),
  ('njp', '백남준아트센터', 'https://njp.ggcf.kr', null, 'unchecked', false, '[3단계/채용+공모/우선2/media_art·curation/경기] 미디어아트 핵심 기관. 공지·공모 경로 실측.'),
  ('gyeongnam_art', '경남도립미술관', 'https://www.gyeongnam.go.kr', null, 'unchecked', false, '[3단계/채용+공모/우선3/curation/경남] 경남도 포털 하위(/gam). 경로 실측.'),
  ('jeonbuk_art', '전북도립미술관', 'https://www.jma.go.kr', null, 'unchecked', false, '[3단계/채용+공모/우선3/curation·residency_open_call/전북] 창작스튜디오 공모 포함. 경로 실측.'),
  ('jeonnam_art', '전남도립미술관', 'https://jnam.jeonnam.go.kr', null, 'unchecked', false, '[3단계/채용+공모/우선3/curation/전남] 경로 실측.'),
  ('jeju_art', '제주도립미술관', 'https://www.jeju.go.kr', null, 'unchecked', false, '[3단계/채용+공모/우선3/curation/제주] 제주도 포털 하위(/jmoa). 경로 실측.'),
  ('suwon_art', '수원시립미술관', 'https://suma.suwon.go.kr', null, 'unchecked', false, '[3단계/채용+공모/우선3/curation·art_education/경기] 경로 실측.'),
  ('cheongju_art', '청주시립미술관', 'https://cmoa.cheongju.go.kr', null, 'unchecked', false, '[3단계/채용+공모/우선3/curation/충북] 경로 실측.'),
  ('sfac', '서울문화재단 채용공고', 'https://www.sfac.or.kr', '/opensquare/notice/recruit_list.do', 'unchecked', false, '[3단계/채용+공모/우선1/all/서울] 입주작가 공모는 /participation/participation/artspace_movein.do (금천예술공장·서울예술창작센터 등). 직원 공채는 recruit.sfac.or.kr.'),
  ('ggcf', '경기문화재단', 'https://www.ggcf.kr', null, 'unchecked', false, '[3단계/채용+공모/우선2/all/경기] 아트누리와 공모 중복 — 공모·지원사업은 아트누리(통합안내)가 모아 오므로 개별 파서는 만들지 않음. 직원 채용만 별도 확인 필요. 채용은 ggcf.saramin.co.kr(사람인 채용관 → 수집 대상 아님). 공모는 경기예술인지원센터(artist.ggcf.kr) 확인.'),
  ('ifac', '인천문화재단', 'https://www.ifac.or.kr', null, 'unchecked', false, '[3단계/채용+공모/우선2/all/인천] 아트누리와 공모 중복 — 공모·지원사업은 아트누리(통합안내)가 모아 오므로 개별 파서는 만들지 않음. 직원 채용만 별도 확인 필요. 채용관 ifac.incruit.com. 인천아트플랫폼 레지던시는 별도(inartplatform).'),
  ('bscf', '부산문화재단', 'https://www.bscf.or.kr', null, 'unchecked', false, '[3단계/채용+공모/우선2/all/부산] 아트누리와 공모 중복 — 공모·지원사업은 아트누리(통합안내)가 모아 오므로 개별 파서는 만들지 않음. 직원 채용만 별도 확인 필요. 채용관 busancf.saramin.co.kr. 홍티아트센터 레지던시 공모 포함.'),
  ('dgfac', '대구문화예술진흥원', 'https://www.dgfac.or.kr', null, 'unchecked', false, '[3단계/채용+공모/우선3/all/대구] 아트누리와 공모 중복 — 공모·지원사업은 아트누리(통합안내)가 모아 오므로 개별 파서는 만들지 않음. 직원 채용만 별도 확인 필요. 도메인·경로 실측(대구예술발전소는 별도 daeguartfactory).'),
  ('gjcf', '광주문화재단 채용공고', 'https://www.gjcf.or.kr', '/cf/news/hire.do', 'unchecked', false, '[3단계/채용+공모/우선2/all/광주] 아트누리와 공모 중복 — 공모·지원사업은 아트누리(통합안내)가 모아 오므로 개별 파서는 만들지 않음. 직원 채용만 별도 확인 필요. 열린광장 > 채용공고.'),
  ('dcaf', '대전문화재단', 'https://www.dcaf.or.kr', null, 'unchecked', false, '[3단계/채용+공모/우선3/all/대전] 아트누리와 공모 중복 — 공모·지원사업은 아트누리(통합안내)가 모아 오므로 개별 파서는 만들지 않음. 직원 채용만 별도 확인 필요. 경로 실측.'),
  ('uctf', '울산문화관광재단', 'https://www.uctf.or.kr', null, 'unchecked', false, '[3단계/채용+공모/우선3/all/울산] 아트누리와 공모 중복 — 공모·지원사업은 아트누리(통합안내)가 모아 오므로 개별 파서는 만들지 않음. 직원 채용만 별도 확인 필요. 채용관 uctf.saramin.co.kr / recruit.incruit.com/uctf. 본 사이트 공고 경로 실측.'),
  ('sjcf', '세종시문화관광재단', 'https://www.sjcf.or.kr', null, 'unchecked', false, '[3단계/채용+공모/우선3/all/세종] 아트누리와 공모 중복 — 공모·지원사업은 아트누리(통합안내)가 모아 오므로 개별 파서는 만들지 않음. 직원 채용만 별도 확인 필요. 경로 실측.'),
  ('gwcf', '강원문화재단', 'https://www.gwcf.or.kr', null, 'unchecked', false, '[3단계/채용+공모/우선3/all/강원] 아트누리와 공모 중복 — 공모·지원사업은 아트누리(통합안내)가 모아 오므로 개별 파서는 만들지 않음. 직원 채용만 별도 확인 필요. 경로 실측. 강원국제트리엔날레 공모 포함 가능.'),
  ('cbfc', '충북문화재단', 'https://www.cbfc.or.kr', null, 'unchecked', false, '[3단계/채용+공모/우선3/all/충북] 아트누리와 공모 중복 — 공모·지원사업은 아트누리(통합안내)가 모아 오므로 개별 파서는 만들지 않음. 직원 채용만 별도 확인 필요. 경로 실측.'),
  ('ctcf', '충남문화관광재단', 'https://www.ctcf.or.kr', null, 'unchecked', false, '[3단계/채용+공모/우선3/all/충남] 아트누리와 공모 중복 — 공모·지원사업은 아트누리(통합안내)가 모아 오므로 개별 파서는 만들지 않음. 직원 채용만 별도 확인 필요. 경로 실측.'),
  ('jbct', '전북문화관광재단', 'https://www.jbct.or.kr', null, 'unchecked', false, '[3단계/채용+공모/우선3/all/전북] 아트누리와 공모 중복 — 공모·지원사업은 아트누리(통합안내)가 모아 오므로 개별 파서는 만들지 않음. 직원 채용만 별도 확인 필요. 경로 실측.'),
  ('jncf', '전남문화재단', 'https://www.jncf.or.kr', null, 'unchecked', false, '[3단계/채용+공모/우선3/all/전남] 아트누리와 공모 중복 — 공모·지원사업은 아트누리(통합안내)가 모아 오므로 개별 파서는 만들지 않음. 직원 채용만 별도 확인 필요. 채용관 jeonnam.saramin.co.kr. 본 사이트 경로 실측.'),
  ('gacf', '경북문화재단', 'http://www.gacf.kr', null, 'unchecked', false, '[3단계/채용+공모/우선3/all/경북] 아트누리와 공모 중복 — 공모·지원사업은 아트누리(통합안내)가 모아 오므로 개별 파서는 만들지 않음. 직원 채용만 별도 확인 필요. https 지원 여부·경로 실측.'),
  ('gcaf', '경남문화예술진흥원 공고', 'https://www.gcaf.or.kr', '/bbs/board.php?bo_table=sub4_1', 'unchecked', false, '[3단계/채용+공모/우선2/all/경남] 아트누리와 공모 중복 — 공모·지원사업은 아트누리(통합안내)가 모아 오므로 개별 파서는 만들지 않음. 직원 채용만 별도 확인 필요. 그누보드 공고 게시판(sub4_1). 마산현대미술관 레지던시 공모 등.'),
  ('jfac', '제주문화예술재단 채용공고', 'http://www.jcaf.or.kr', '/contents/index.php?mid=070102', 'unchecked', false, '[3단계/채용+공모/우선2/all/제주] 아트누리와 공모 중복 — 공모·지원사업은 아트누리(통합안내)가 모아 오므로 개별 파서는 만들지 않음. 직원 채용만 별도 확인 필요. 채용관 recruit.incruit.com/jfac. 레지던시 입주작가 통합공모 매년 게시.'),
  ('inartplatform', '인천아트플랫폼 공지사항', 'https://inartplatform.kr', null, 'unchecked', false, '[4단계/채용+공모/우선2/residency_open_call·curation/인천] 추정 목록 주소(/notice)는 404. 상세 /notice/view?no=… 확인됨 → 목록 주소 실측. 레지던시 입주작가 공모·인턴 채용.'),
  ('daeguartfactory', '대구예술발전소 공지사항', 'https://www.daeguartfactory.kr', '/front/board/list.php?code=notice', 'unchecked', false, '[4단계/채용+공모/우선2/residency_open_call/대구] 상세 /front/board/view.php?code=notice&no=… 확인됨. 매년 12월 레지던시 입주작가 모집.'),
  ('nabi', '아트센터 나비', 'https://www.nabi.or.kr', '/page/board_list.php?brd_id=project', 'unchecked', false, '[4단계/채용+공모/우선3/media_art·residency_open_call/서울] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 상세 /page/board_view.php?brd_id=project 확인됨. 나비 아티스트 레지던시(미디어아트).'),
  ('namjunepaik', '백남준문화재단 미디어아트 공모', 'https://namjunepaik.org', null, 'unchecked', false, '[4단계/공모/우선3/media_art/전국·온라인] 연 1회 미디어아트 공모전(39세 이하). 상세 /media-art-competition-2025 확인됨.'),
  ('gwangjubiennale', '광주비엔날레', 'https://www.gwangjubiennale.org', null, 'unchecked', false, '[4단계/채용+공모/우선2/curation·art_management/광주] 채용·전시기획자양성과정 모집. 공지 경로 실측.'),
  ('busanbiennale', '부산비엔날레 채용공고', 'http://www.busanbiennale.org', '/BBOCkr/index.php?pCode=gongo&mode=list', 'unchecked', false, '[4단계/채용/우선2/curation·art_management/부산] https 지원 여부 확인.'),
  ('changwon_biennale', '창원조각비엔날레(창원문화재단)', 'https://www.changwonbiennale.or.kr', null, 'unchecked', false, '[4단계/채용+공모/우선3/sculpture_installation·curation/경남] 조각 분야 핵심 행사. 조직위 채용·참여작가 공모. 경로 실측.'),
  ('okcj', '청주공예비엔날레', 'https://www.okcj.org', null, 'unchecked', false, '[4단계/채용+공모/우선3/craft·curation/충북] 조직위 기간제 채용·공예 공모. 경로 실측.'),
  ('leeum', '리움미술관 공지', 'https://www.leeumhoam.org', '/leeum/info/notice', 'unchecked', false, '[4단계/채용/우선3/curation·art_education/서울] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 공지에 채용이 섞여 있음. 자바스크립트 렌더링 여부 실측. 사립 → 서면 협의.'),
  ('museumhanmi', '뮤지엄한미 공모(MH Talent Portfolio)', 'https://museumhanmi.or.kr', null, 'unchecked', false, '[4단계/채용+공모/우선3/photography/서울] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 사진 분야 작가 포트폴리오 공모. 공지 경로 실측.'),
  ('goeun', '고은사진미술관', 'https://www.goeunmuseum.kr', null, 'unchecked', false, '[4단계/채용+공모/우선3/photography/부산] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 사진 분야. 공지 경로 실측.'),
  ('artsonje', '아트선재센터', 'https://artsonje.org', null, 'unchecked', false, '[4단계/채용/우선3/curation/서울] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 사립. 채용 공지 경로·협의.'),
  ('ilmin', '일민미술관', 'https://ilmin.org', null, 'unchecked', false, '[4단계/채용/우선3/curation/서울] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 사립. 채용 공지 경로·협의.'),
  ('apma', '아모레퍼시픽미술관', 'https://apma.amorepacific.com', null, 'unchecked', false, '[4단계/채용/우선3/curation/서울] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 사립. 채용은 그룹 채용사이트로 갈 가능성 → 확인.'),
  ('songeun', '송은', 'https://www.songeun.or.kr', null, 'unchecked', false, '[4단계/채용+공모/우선3/curation·residency_open_call/서울] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 송은미술대상 공모·채용. 경로 실측.'),
  ('kiaf', '키아프 서울(한국화랑협회)', 'https://kiaf.org', null, 'unchecked', false, '[4단계/채용/우선3/art_management/서울] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 아트페어 스태프 채용. 경로 실측.'),
  ('alio_api', '잡알리오 공공기관 채용정보(공공데이터 API)', 'https://job.alio.go.kr', null, 'unchecked', false, '[5단계/채용/우선2/curation·art_management·art_education/전국·온라인] 공공데이터포털 ''재정경제부_공공기관 채용정보 조회서비스''(data.go.kr/data/15125273) 인증키 신청 후 사용. 예술경영지원센터·문화예술위원회·ACC재단·KCDF·문화예술교육진흥원·국립박물관문화재단 등 기관코드로 필터.'),
  ('work24_api', '고용24(워크넷) 채용정보 API', 'https://www.work24.go.kr', null, 'unchecked', false, '[5단계/채용/우선3/all/전국·온라인] 공공데이터포털 워크넷 채용정보 API. 직종코드(문화·예술·디자인)로 필터. 공고량은 많으나 예술 특화도는 낮음.'),
  ('contestkorea', '콘테스트코리아 미술·디자인 공모전', 'https://www.contestkorea.com', '/sub/list.php?int_gbn=1&Txt_bcode=030610001', 'unchecked', false, '[5단계/공모/우선3/painting·print_drawing·media_art·photography/전국·온라인] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 미술·디자인·웹툰 분류. 디자인·웹툰은 제목 키워드로 제외.'),
  ('wevity', '위비티 예체능·미술 공모전', 'https://www.wevity.com', null, 'unchecked', false, '[5단계/공모/우선3/painting·photography·media_art/전국·온라인] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 분야 필터 파라미터 실측. 민간 → 협의.'),
  ('thinkcontest', '씽굿 공모전', 'https://www.thinkcontest.com', '/Contest/CateField.html?c=8', 'unchecked', false, '[5단계/공모/우선3/painting·photography·media_art/전국·온라인] 민간·협의대기 — 서면 협의 전까지 수집하지 않음. 분야 코드(c=8)가 미술인지 실측. 민간 → 협의.')
on conflict (code) do update set
  name = excluded.name,
  base_url = excluded.base_url,
  list_path = excluded.list_path,
  note = excluded.note;
